version: '2'
services:
 postgres:
   image: postgres:9.6
   ports:
     - "5432:5432"
   environment:
     - POSTGRES_DB=home_on
     - POSTGRES_USER=home
     - POSTGRES_PASSWORD=on
     - MAX_CONNECTIONS=100
 stubby4j:
   image: sandokandias/stubby4j-docker
   ports:
     - "8882:8882"
   environment:
     STUBBY_PORT: 8882
   volumes:
     - ./documents/stubby4j/stubby.yml:/usr/local/stubby.yml
