# LOGGING
logging:
  file: target/home-on.log
  level:
    org.home.on: DEBUG
    org.springframework: INFO
    org.hibernate: INFO

# DATABASE
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/homeon
    username: homeon
    password: homeon
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

# SECURITY
security:
  password:
    secret: secret

# LIQUIBASE
liquibase:
  enabled: true
  change-log: classpath:liquibase/config/master.xml
  url: jdbc:postgresql://localhost:5432/homeon
  user: homeon
  password: homeon
